import Link from 'next/link';
import {useState} from 'react';
import ResearchPage from '../components/ResearchPage';

type Point = {x?:number;y1?:number;y2?:number;y3?:number};
type Signal = {id:string; content:string; graph1:Point[]; graph2:Point[]; graph3?:Point[]; likes:number; comments:number; shares:number};
function Chart({points, tone='green'}:{points:Point[]; tone?:'green'|'purple'}) { const values=points.map(p=>Number(p.y1 ?? p.y2 ?? p.y3)).filter(Number.isFinite); if(values.length<2)return null; const min=Math.min(...values), max=Math.max(...values), range=max-min||1; const coords=values.map((v,i)=>`${(i/(values.length-1))*100},${100-((v-min)/range)*88-6}`).join(' '); return <svg className="signal-chart" viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="Stock signal chart"><polyline points={coords} fill="none" stroke={tone === 'purple' ? '#b56cff' : '#35d477'} strokeWidth="2" vectorEffect="non-scaling-stroke" /></svg>; }
function SignalCard({item}:{item:Signal}) { const [metric,setMetric]=useState<'price'|'financial'|'technical'>('price'); const points=metric==='price'?item.graph1:metric==='financial'?item.graph2:(item.graph3||[]); const title=metric==='price'?'PRICE TREND':metric==='financial'?'FINANCIAL PREDICTION':'TECHNICAL METRICS'; const tone=metric==='price'?'green':'purple'; return <Link className="research-card research-card-compact signal-card" href={`/insight_details_page?signalId=${encodeURIComponent(item.id)}`}><span className="insight-bubble">STOCK SETUP →</span><div className="metric-switcher">{[['price','Price'],['financial','Financial'],['technical','Technical']].map(([value,label])=><button key={value} className={metric===value?'active':''} onClick={e=>{e.preventDefault();e.stopPropagation();setMetric(value as typeof metric);}}>{label}</button>)}</div><div className={`chart-label ${tone==='purple'?'prediction-label':'price-label'}`}>{title}</div>{points.length>1?<Chart points={points} tone={tone}/>:<div className="metric-locked">Check in the app for more metrics</div>}<h2>{item.content.split(/\r?\n/).map(x=>x.trim()).find(Boolean) || 'New stock prediction setup'}</h2><div className="prediction-badge">PREDICTION ↗</div></Link>; }
export default function StocksToBuy({items}:{items:Signal[]}) { return <ResearchPage title="Stocks to buy now: latest signals" path="/stocks-to-buy"><div className="hero"><span className="eyebrow">STOCK BUY SIGNALS</span><h1>Stocks to buy now</h1><p>Recent stock setups and market signals. Open each insight in the app for the full analysis.</p></div><div className="research-board">{items.map(item=><SignalCard item={item} key={item.id}/>)}</div></ResearchPage>; }
export async function getStaticProps() { let items:Signal[]=[]; try { const r=await fetch('https://us-central1-stocker-fcda2.cloudfunctions.net/stockSignals'); if(r.ok) items=(await r.json()).items||[]; } catch (_) {} return {props:{items},revalidate:1800}; }
